name: "CD: Main Workflow"

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        run: yarn build
      - name: Run deploy
        run: yarn deploy